### PR TITLE
Only login when needed

### PR DESCRIPTION
**Pull request by strk**
Greately speeds up commands like "help"

### CODE REVIEW

**Comment by strk** [comment]
It would be also useful to save session cookies, to avoid more than a single GET on every single command

**Comment by strk** [comment]
@tamentis don't you like this approach ? I've started using cartman with trac.osgeo.org and I'm often slowed down by these upfront requests for no reason...

**Comment by tamentis** [comment]
I don't like adding a `login()` call in `get()`.  Ideally I would prefer to do two things:
1. like you said, save session cookies
2. flag which commands require login (maybe a decorator)

**Comment by strk** [comment]
Some commands would still benefit from controlling when login happens. See the 'comment' command for example: immediately starting the editor and postponing login is a better experience

**Comment by tamentis** [comment]
Agreed, then for the purpose of that PR, I would rather see `self.login()` in the right places for specific commands than a parameter to `.get()`

**Comment by strk** [comment]
My assumption was that "the right place" is really whenever a "get"
or a "post" are needed.

It can be some "get" which do not need authentication (like the one
to send login) thus the added parameter.

It's much less intrusive that way.

**Comment by tamentis** [comment]
I'd like to keep `get()` as a wrapper around the HTTP `GET` method which implies a single query.  I also don't like inverse flags  like `nologin` and even though calling `self.login()` is more intrusive, it is a more explicit representation of what is actually going on to make that command work.

**Comment by strk** [comment]
inverse flag is gone, the other arguments still hold :)

**Comment by strk** [comment]
Alright, now changed to explicit call. See if you like it now.

**Comment by tamentis** [comment]
Awesome, thank you :)

**Pull request merged**
